$out_dir = '../';
$jobname = 'Report';
$out_name = 'Report';

# Build glossary and acronym lists automatically when their source files change.
add_cus_dep('glo', 'gls', 0, 'makeglossaries');
add_cus_dep('acn', 'acr', 0, 'makeglossaries');

sub makeglossaries {
    my ($base_name, $path) = fileparse($_[0]);
    pushd($path);
    my $return = system('makeglossaries', $base_name);
    popd();
    return $return;
}

$clean_ext .= ' acr acn alg glo gls glg';